/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package View;

/**
 *
 * @author asus
 */
import Controlador.ClienteControlador;

import javax.swing.*;

public class ClienteGUI extends javax.swing.JFrame {

    private final ClienteControlador control = new ClienteControlador();
    /**
     * Creates new form EstudianteGUI
     */
    public ClienteGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        opcion = new javax.swing.JComboBox<>();
        nombre = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelNumeroContacto = new javax.swing.JLabel();
        labelMascotasACargo = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        numeroContacto = new javax.swing.JTextField();
        mascotasACargo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        botonInstrucciones = new javax.swing.JButton();
        labelIdentificacion = new javax.swing.JLabel();
        identificacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAceptar.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel1.setText("Seleccione una de las opciones");

        opcion.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar cliente", "Consultar cliente", "Actualizar cliente", "Listar clientes", "Eliminar cliente" }));
        opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActionPerformed(evt);
            }
        });

        nombre.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        labelNombre.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        labelNombre.setText("Nombre(s)");

        labelDireccion.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        labelDireccion.setText("Dirección");

        labelNumeroContacto.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        labelNumeroContacto.setText("Numero de contacto");

        labelMascotasACargo.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        labelMascotasACargo.setText("Mascotas a cargo");

        direccion.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        numeroContacto.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        mascotasACargo.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Clientes");

        botonInstrucciones.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        botonInstrucciones.setText("Instrucciones");
        botonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInstruccionesActionPerformed(evt);
            }
        });

        labelIdentificacion.setText("Identificación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelIdentificacion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonInstrucciones)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDireccion)
                                    .addComponent(labelNumeroContacto)
                                    .addComponent(labelNombre)
                                    .addComponent(labelMascotasACargo))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mascotasACargo, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(direccion)
                                    .addComponent(numeroContacto)
                                    .addComponent(identificacion))))
                        .addContainerGap(137, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonInstrucciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDireccion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeroContacto)
                    .addComponent(numeroContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMascotasACargo)
                    .addComponent(mascotasACargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentificacion)
                    .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(botonAceptar)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Agregar cliente":
                control.almacenarCliente(identificacion.getText().trim().toUpperCase(), nombre.getText().trim().toUpperCase(),
                        direccion.getText().trim().toUpperCase(), numeroContacto.getText().trim());
                break;
            case "Consultar cliente":
                control.consultarCliente(identificacion.getText().trim());
                break;
            case "Actualizar cliente":
                control.actualizarCliente(identificacion.getText().trim().toUpperCase(), nombre.getText().trim().toUpperCase(),
                        direccion.getText().trim().toUpperCase(), numeroContacto.getText().trim());
                break;
            case "Listar clientes":
                control.listarClientes();
                break;
            case "Eliminar cliente":
                control.eliminarCliente(identificacion.getText().trim());
                break;
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Agregar cliente":
                activarTodo();                
                break;
            case "Consultar cliente":
                activarSoloIdentificacion();
                break;
            case "Actualizar cliente":
                activarTodo();
                break;
            case "Listar clientes":
                activarSoloIdentificacion();
                labelIdentificacion.setEnabled(false);
                identificacion.setEnabled(false);
                break;
            case "Eliminar cliente":
                activarSoloIdentificacion();
                break;
        }
    }//GEN-LAST:event_opcionActionPerformed

    private void botonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInstruccionesActionPerformed
        InstruccionesClientes instrucciones = new InstruccionesClientes();
        instrucciones.setVisible(true);
    }//GEN-LAST:event_botonInstruccionesActionPerformed
    
    public void activarTodo(){
        labelNombre.setEnabled(true);
        nombre.setEnabled(true);
        labelDireccion.setEnabled(true);
        direccion.setEnabled(true);
        labelMascotasACargo.setEnabled(true);
        mascotasACargo.setEnabled(true);
        labelNumeroContacto.setEnabled(true);
        numeroContacto.setEnabled(true);
        labelIdentificacion.setEnabled(true);
        identificacion.setEnabled(true);
    }
    
    public void activarSoloIdentificacion(){
        labelNombre.setEnabled(false);
        nombre.setEnabled(false);
        labelDireccion.setEnabled(false);
        direccion.setEnabled(false);
        labelMascotasACargo.setEnabled(false);
        mascotasACargo.setEnabled(false);
        labelNumeroContacto.setEnabled(false);
        numeroContacto.setEnabled(false);
        labelIdentificacion.setEnabled(true);
        identificacion.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonInstrucciones;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField identificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelIdentificacion;
    private javax.swing.JLabel labelMascotasACargo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumeroContacto;
    private javax.swing.JTextField mascotasACargo;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numeroContacto;
    private javax.swing.JComboBox<String> opcion;
    // End of variables declaration//GEN-END:variables
}
