/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package View;

/**
 *
 * @author asus
 */
import Controlador.MascotaControlador;

import javax.swing.*;

public class MascotaGUI extends javax.swing.JFrame {

    private final MascotaControlador control = new MascotaControlador();
    /**
     * Creates new form EstudianteGUI
     */
    public MascotaGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        botonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        opcion = new javax.swing.JComboBox<>();
        nombre = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        labelRaza = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelVacunas = new javax.swing.JLabel();
        raza = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        vacunas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        botonInstrucciones = new javax.swing.JButton();
        labelTipo = new javax.swing.JLabel();
        tipo = new javax.swing.JTextField();
        labelIdentificacion = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        labelFechaIngreso = new javax.swing.JLabel();
        identificacion = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        fechaIngreso = new javax.swing.JTextField();
        labelLugarOrigen = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        lugarOrigen = new javax.swing.JTextField();
        genero = new javax.swing.JTextField();
        opcionEstado = new javax.swing.JComboBox<>();
        precio = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAceptar.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel1.setText("Seleccione una de las opciones");

        opcion.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar mascota", "Consultar mascota", "Actualizar mascota", "Listar mascota", "Vender mascota" }));
        opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActionPerformed(evt);
            }
        });

        nombre.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        labelNombre.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        labelNombre.setText("Nombre(s)");

        labelRaza.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        labelRaza.setText("Raza");

        labelEdad.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        labelEdad.setText("Edad");

        labelVacunas.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        labelVacunas.setText("Vacunas");

        raza.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        edad.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        vacunas.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Registro de mascotas");

        botonInstrucciones.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        botonInstrucciones.setText("Instrucciones");
        botonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInstruccionesActionPerformed(evt);
            }
        });

        labelTipo.setText("Tipo");

        labelIdentificacion.setText("Identificacion");

        labelPeso.setText("Peso");

        labelFechaIngreso.setText("Fecha Ingreso");

        labelLugarOrigen.setText("Lugar Origen");

        labelGenero.setText("Genero");

        labelEstado.setText("Es adoptado");

        opcionEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        precio.setText("Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 97, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(52, 52, 52)
                                .addComponent(botonInstrucciones))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelGenero)
                                .addGap(172, 172, 172)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(opcionEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(edad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(raza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(tipo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(vacunas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(identificacion, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(peso, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fechaIngreso, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lugarOrigen, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(genero, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLugarOrigen)
                            .addComponent(labelFechaIngreso)
                            .addComponent(labelPeso)
                            .addComponent(labelIdentificacion)
                            .addComponent(labelTipo)
                            .addComponent(labelVacunas)
                            .addComponent(labelEdad)
                            .addComponent(labelRaza)
                            .addComponent(labelNombre)
                            .addComponent(jLabel1)
                            .addComponent(labelEstado)
                            .addComponent(precio))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(botonInstrucciones))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRaza)
                            .addComponent(raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEdad)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelVacunas)
                            .addComponent(vacunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTipo)
                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdentificacion)
                            .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPeso)
                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFechaIngreso)
                            .addComponent(fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLugarOrigen)
                            .addComponent(lugarOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGenero)
                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEstado)
                            .addComponent(opcionEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precio)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Agregar mascota":
                control.almacenarMascota(
                    nombre.getText().trim().toUpperCase(),
                    raza.getText().trim().toUpperCase(),
                    Integer.parseInt(edad.getText().trim()),
                    vacunas.getText().trim().toUpperCase(),
                    tipo.getText().trim().toUpperCase(),
                    identificacion.getText().trim(),
                    Double.parseDouble(peso.getText().trim()),
                    fechaIngreso.getText().trim(),
                    lugarOrigen.getText().trim().toUpperCase(),
                    genero.getText().trim().toUpperCase().charAt(0),
                    Double.parseDouble(precio.getText().trim()),
                    (opcionEstado.getSelectedItem().toString().equalsIgnoreCase("SI"))
                );
                break;
            case "Consultar mascota":
                control.consultarMascota(identificacion.getText().trim());
                break;
            case "Actualizar mascota":
                control.almacenarMascota(
                    nombre.getText().trim().toUpperCase(),
                    raza.getText().trim().toUpperCase(),
                    Integer.parseInt(edad.getText().trim()),
                    vacunas.getText().trim().toUpperCase(),
                    tipo.getText().trim().toUpperCase(),
                    identificacion.getText().trim(),
                    Double.parseDouble(peso.getText().trim()),
                    fechaIngreso.getText().trim(),
                    lugarOrigen.getText().trim().toUpperCase(),
                    genero.getText().trim().toUpperCase().charAt(0),
                    Double.parseDouble(precio.getText().trim()),
                    (opcionEstado.getSelectedItem().toString().equalsIgnoreCase("SI"))
                );
                break;
            case "Listar mascota":
                control.listarMascotas();
                break;
            case "Vender mascota":
                control.eliminarMascota(identificacion.getText().trim());
                break;
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Agregar mascota":
                activarTodo();                
                break;
            case "Consultar mascota":
                activarSoloIdentificacion();
                break;
            case "Actualizar mascota":
                activarTodo();
                break;
            case "Listar mascota":
                activarSoloIdentificacion();
                labelIdentificacion.setEnabled(false);
                identificacion.setEnabled(false);
                break;
            case "Vender mascota":
                activarSoloIdentificacion();
                break;
        }
    }//GEN-LAST:event_opcionActionPerformed

    private void botonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInstruccionesActionPerformed
        InstruccionesMascotas instrucciones = new InstruccionesMascotas();
        instrucciones.setVisible(true);
    }//GEN-LAST:event_botonInstruccionesActionPerformed
    
    public void activarTodo(){
        labelNombre.setEnabled(true);
        nombre.setEnabled(true);
        labelRaza.setEnabled(true);
        raza.setEnabled(true);
        labelVacunas.setEnabled(true);
        vacunas.setEnabled(true);
        labelEdad.setEnabled(true);
        edad.setEnabled(true);
        labelTipo.setEnabled(true);
        tipo.setEnabled(true);
        labelIdentificacion.setEnabled(true);
        identificacion.setEnabled(true);
        labelPeso.setEnabled(true);
        peso.setEnabled(true);
        labelEstado.setEnabled(true);
        opcionEstado.setEnabled(true);
        labelFechaIngreso.setEnabled(true);
        fechaIngreso.setEnabled(true);
        labelLugarOrigen.setEnabled(true);
        lugarOrigen.setEnabled(true);
        labelGenero.setEnabled(true);
        genero.setEnabled(true);
        
    }
    
    public void activarSoloIdentificacion(){
        labelNombre.setEnabled(false);
        nombre.setEnabled(false);
        labelRaza.setEnabled(false);
        raza.setEnabled(false);
        labelVacunas.setEnabled(false);
        vacunas.setEnabled(false);
        labelEdad.setEnabled(false);
        edad.setEnabled(false);
        labelTipo.setEnabled(false);
        tipo.setEnabled(false);
        labelIdentificacion.setEnabled(true);
        identificacion.setEnabled(true);
        labelPeso.setEnabled(false);
        peso.setEnabled(false);
        labelEstado.setEnabled(false);
        opcionEstado.setEnabled(false);
        labelFechaIngreso.setEnabled(false);
        fechaIngreso.setEnabled(false);
        labelLugarOrigen.setEnabled(false);
        lugarOrigen.setEnabled(false);
        labelGenero.setEnabled(false);
        genero.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MascotaGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonInstrucciones;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField fechaIngreso;
    private javax.swing.JTextField genero;
    private javax.swing.JTextField identificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFechaIngreso;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelIdentificacion;
    private javax.swing.JLabel labelLugarOrigen;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelRaza;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelVacunas;
    private javax.swing.JTextField lugarOrigen;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> opcion;
    private javax.swing.JComboBox<String> opcionEstado;
    private javax.swing.JTextField peso;
    private javax.swing.JLabel precio;
    private javax.swing.JTextField raza;
    private javax.swing.JTextField tipo;
    private javax.swing.JTextField vacunas;
    // End of variables declaration//GEN-END:variables
}
